"""Initial Migration

Revision ID: 875f6f8f9120
Revises: 2ffc8fd37f41
Create Date: 2020-09-28 11:07:26.521635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875f6f8f9120'
down_revision = '2ffc8fd37f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
